/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.1
 * Generated at: 2017-12-09 17:13:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class P_005fadd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/apache-tomcat-9.0.1/lib/standard.jar", Long.valueOf(1098678824000L));
    _jspx_dependants.put("jar:file:/C:/apache-tomcat-9.0.1/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"kr\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>http://www.blueb.co.kr</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://netdna.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css\">\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("<!-- 부가적인 테마 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 자바스크립트 -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("input[type=\"checkbox\"]#menu_state {\r\n");
      out.write("  display: none;\r\n");
      out.write("}\r\n");
      out.write("input[type=\"checkbox\"]:checked ~ nav {\r\n");
      out.write("  width: 250px;\r\n");
      out.write("}\r\n");
      out.write("input[type=\"checkbox\"]:checked ~ nav label[for=\"menu_state\"] i::before {\r\n");
      out.write("  content: \"\\f053\";\r\n");
      out.write("}\r\n");
      out.write("input[type=\"checkbox\"]:checked ~ nav ul {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write("input[type=\"checkbox\"]:checked ~ nav ul li a i {\r\n");
      out.write("  border-right: 1px solid #2f343e;\r\n");
      out.write("}\r\n");
      out.write("input[type=\"checkbox\"]:checked ~ nav ul li a span {\r\n");
      out.write("  opacity: 1;\r\n");
      out.write("  transition: opacity 0.25s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("input[type=\"checkbox\"]:checked ~ main {\r\n");
      out.write("  left: 250px;\r\n");
      out.write("}\r\n");
      out.write("nav {\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  z-index: 9;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  bottom: 0;\r\n");
      out.write("  background: #383e49;\r\n");
      out.write("  color: #9aa3a8;\r\n");
      out.write("  width: 50px;\r\n");
      out.write("  font-family: 'Montserrat', sans-serif;\r\n");
      out.write("  font-weight: lighter;\r\n");
      out.write("  transition: all 0.15s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("nav label[for=\"menu_state\"] i {\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  right: -8px;\r\n");
      out.write("  box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);\r\n");
      out.write("  background: #fff;\r\n");
      out.write("  font-size: 10px;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  height: 15px;\r\n");
      out.write("  width: 15px;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("  border: 1px solid #ddd;\r\n");
      out.write("  transition: width 0.15s ease-in-out;\r\n");
      out.write("  z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("nav label[for=\"menu_state\"] i::before {\r\n");
      out.write("  margin-top: 2px;\r\n");
      out.write("  content: \"\\f054\";\r\n");
      out.write("}\r\n");
      out.write("nav label[for=\"menu_state\"] i:hover {\r\n");
      out.write("  box-shadow: 0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23);\r\n");
      out.write("}\r\n");
      out.write("nav ul {\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  display: block;\r\n");
      out.write("  width: 50px;\r\n");
      out.write("  list-style-type: none;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("}\r\n");
      out.write("nav ul li {\r\n");
      out.write("  border: 1px solid #2f343e;\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write("nav ul li.unread:after {\r\n");
      out.write("  content: attr(data-content);\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 10px;\r\n");
      out.write("  left: 25px;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  width: 15px;\r\n");
      out.write("  height: 15px;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  background: #ef5952;\r\n");
      out.write("  font-size: 8px;\r\n");
      out.write("}\r\n");
      out.write("nav ul li:not(:last-child) {\r\n");
      out.write("  border-bottom: none;\r\n");
      out.write("}\r\n");
      out.write("nav ul li.active a {\r\n");
      out.write("  background: #4c515d;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("}\r\n");
      out.write("nav ul li a {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  display: block;\r\n");
      out.write("  white-space: nowrap;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  color: #9aa3a8;\r\n");
      out.write("  height: 50px;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  transition: all 0.15s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("nav ul li a:hover {\r\n");
      out.write("  background: #4c515d;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("}\r\n");
      out.write("nav ul li a * {\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("nav ul li a i {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  width: 50px;\r\n");
      out.write("  z-index: 999999;\r\n");
      out.write("}\r\n");
      out.write("nav ul li a i.fa {\r\n");
      out.write("  line-height: 50px;\r\n");
      out.write("}\r\n");
      out.write("nav ul li a span {\r\n");
      out.write("  padding-left: 25px;\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("  line-height: 50px;\r\n");
      out.write("  transition: opacity 0.1s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<input type=\"checkbox\" id=\"menu_state\" checked>\r\n");
      out.write("<nav>\r\n");
      out.write("\t<label for=\"menu_state\"><i class=\"fa\"></i></label>\r\n");
      out.write("\t<ul>\r\n");
      out.write("    <li>\r\n");
      out.write("      <a href=\"main.do\">\r\n");
      out.write("        <i class=\"glyphicon glyphicon-home\"></i>\r\n");
      out.write("        <span>메인으로</span>   <!--환자 대기 목록,병실 목록 및 현황-->\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\t\t\t<a href=\"P_addui.do\">\r\n");
      out.write("\t\t\t\t<i class=\"glyphicon glyphicon-plus\"></i>\r\n");
      out.write("\t\t\t\t<span>환자 추가</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\t\t\t<a href=\"D_addui.do\">\r\n");
      out.write("\t\t\t\t<i class=\"glyphicon glyphicon-plus\"></i>\r\n");
      out.write("\t\t\t\t<span>의사 추가</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\t\t\t<a href=\"D_clsif.do\">\r\n");
      out.write("\t\t\t\t<i class=\"glyphicon glyphicon-calendar\"></i>\r\n");
      out.write("\t\t\t\t<span>의사 부서 정보</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\t\t\t<a href=\"cristal.do\">\r\n");
      out.write("\t\t\t\t<i class=\"glyphicon glyphicon-pencil\"></i>\r\n");
      out.write("\t\t\t\t<span>환자 수정</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\t\t\t<a href=\"delsel.do\">\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-trash\"></i>\r\n");
      out.write("\t\t\t\t<span>환자 삭제</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("      <li>\r\n");
      out.write("      <a href=\"insel.do\">\r\n");
      out.write("        <i class=\"glyphicon glyphicon-log-in\"></i>\r\n");
      out.write("        <span>입실</span>\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("        <li>\r\n");
      out.write("      <a href=\"javascript:void(0)\">\r\n");
      out.write("        <i class=\"glyphicon glyphicon-log-out\"></i>\r\n");
      out.write("        <span>퇴실</span>\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("<section style=\"position:absolute; top:50px;left:300px\">\r\n");
      out.write("\t<form class=\"form-horizontal\" action =\"P_add.do\" method=\"post\">\r\n");
      out.write("  <div class=\"form-group form-group-lg\">\r\n");
      out.write("    <label class=\"col-sm-2 control-label\" for=\"formGroupInputLarge\">이름</label>\r\n");
      out.write("    <div class=\"col-sm-10\">\r\n");
      out.write("      <input class=\"form-control\" type=\"text\" id=\"formGroupInputLarge\" placeholder=\"이름\" name =\"P_NAME\">\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group form-group-lg\">\r\n");
      out.write("      <label class=\"col-sm-2 control-label\" for=\"formGroupInputLarge\">주민번호</label>\r\n");
      out.write("    <div class=\"col-sm-10\">\r\n");
      out.write("      <input class=\"form-control\" type=\"text\" id=\"formGroupInputLarge\" placeholder=\"주민번호\" name =\"P_PERNUM\">\r\n");
      out.write("    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<select name =\"P_GENDER\">\r\n");
      out.write("\t\t<option value=\"남자\">남자</option>\r\n");
      out.write("\t\t<option value=\"여자\">여자</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("\r\n");
      out.write("\t<input type=\"submit\" value=\"저장\" class=\"btn btn-default\">\t\r\n");
      out.write("</form>\r\n");
      out.write("\t\r\n");
      out.write("</section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
